# Generated by Django 4.1.2 on 2022-10-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
