# Generated by Django 4.1.2 on 2022-10-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction_listings',
            new_name='Auction_listing',
        ),
    ]
