# Generated by Django 4.1.2 on 2022-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auction_listings_auction_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('item', models.CharField(max_length=64)),
                ('bid_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
