# Generated by Django 4.1.2 on 2022-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_alter_auction_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='image',
            field=models.URLField(),
        ),
    ]
