# Generated by Django 4.1.2 on 2022-10-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listing_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bid',
            new_name='Bid_price',
        ),
    ]
