# Generated by Django 4.1.2 on 2022-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bid_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid_price',
            name='item',
            field=models.IntegerField(),
        ),
    ]
