# Generated by Django 4.1.2 on 2022-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='item',
            field=models.IntegerField(),
        ),
    ]
