# Generated by Django 4.1.2 on 2022-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_wish_list_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closebid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('item', models.IntegerField()),
                ('highest_bid', models.IntegerField()),
            ],
        ),
    ]
