# Generated by Django 4.1.2 on 2022-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_closebid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closebid',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='closebid',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
