# Generated by Django 4.1.2 on 2022-10-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_closebid_highest_bid_closebid_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('item', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
