# Generated by Django 4.1.2 on 2022-10-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
